<?php


namespace Sales\Providers;


use Illuminate\Support\ServiceProvider;
use Sales\Hook\SalesHook;

class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
        add_action('wadmin-register-menu',[SalesHook::class,'handle'],6);
    }
}
