<?php

namespace Wallets\Providers;

use Illuminate\Support\ServiceProvider;
use Wallets\Hook\WalletHook;

class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
        add_action('wadmin-register-menu',[WalletHook::class,'handle'],30);
    }
}
