<?php

namespace ZaloZns\Providers;
use Illuminate\Support\ServiceProvider;
use ZaloZns\Hook\ZaloZnsHook;
class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
        add_action('wadmin-register-menu',[ZaloZnsHook::class,'handle'],35);
    }
}
