<?php

namespace Logs\Providers;
use Illuminate\Support\ServiceProvider;
use Logs\Hook\LogsHook;

class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
        add_action('wadmin-register-menu',[LogsHook::class,'handle'],45);
    }
}
