<?php


namespace Video\Providers;


use Illuminate\Support\ServiceProvider;
use Video\Hook\VideoHook;


class HookProvider extends ServiceProvider
{
    public function boot(){
        $this->app->booted(function (){
            $this->booted();
        });
    }
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function booted(){
//        add_action('wadmin-register-menu',[VideoHook::class,'handle'],22);
    }
}
